export let routes = {
  default: "/",
  Page: "/folder/:name",
  home: "/home",
  submit_job: "/submit-job",
  login: "/login",
  Chatroom: "/chatroom/:id",
  ChatroomList: "/Chatroom",
  ProfilePage: "/profile",
  SettingPage: "/settings",
  Blockchain: "/Blockchain",
  test: "/test",
  welcome: "/welcome",
  DownloadKey: "/DownloadKey",
  DrawKey: "/DrawKey",
  Edit: "/Demo/Edit",
  Create: "/Demo/Create",
  register: "/register",
  othersProfilePage: (user_id: string | number) => `/profile/${user_id}`,
  BookmarkList: "/bookmarks",
  MyJobList: "/my-jobs",
};
