export let routes = {
  default: "/",
  Page: "/folder/:name",
  home: "/home",
  submit_job: "/submit-job",
  login: "/login",
  Chatroom: "/Chatroom",
  ChatroomList: "/ChatroomList",
  ProfilePage: "/ProfilePage",
  SettingPage: "/SettingPage",
  Blockchain: "/Blockchain",
  test: "/test",
  welcome: "/welcome",
  DownloadKey: "/DownloadKey",
  DrawKey: "/DrawKey",
  Edit: "/Demo/Edit",
  Create: "/Demo/Create",
  register: "/register",
};
